//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowersOfAttorneyServerExtension {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowersOfAttorneyServerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application for revocation of the power of attorney.
        /// </summary>
        internal static string ApplicationForRevocationOfThePowerOfAttorney {
            get {
                return ResourceManager.GetString("ApplicationForRevocationOfThePowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancellation of the power of attorney by the principal.
        /// </summary>
        internal static string CancellationOfThePowerOfAttorneyByThePrincipal {
            get {
                return ResourceManager.GetString("CancellationOfThePowerOfAttorneyByThePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrust of general format of powers of attorney has not been implemented.
        /// </summary>
        internal static string EmchdRetrustNotImplemented {
            get {
                return ResourceManager.GetString("EmchdRetrustNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get value of the name of the authority that issued representative identification document.
        /// </summary>
        internal static string Error_AuthIssIDDoc {
            get {
                return ResourceManager.GetString("Error_AuthIssIDDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of issue of identity document of head of the organization is not specified.
        /// </summary>
        internal static string Error_DateIssCEOIDDocIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateIssCEOIDDocIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of issue of representative&apos;s identity document is not specified.
        /// </summary>
        internal static string Error_DateIssReprIDDocIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateIssReprIDDocIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date and time of the signature are not specified.
        /// </summary>
        internal static string Error_DateTimeOfSignatureIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateTimeOfSignatureIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not get the data of the head of the organization.
        /// </summary>
        internal static string Error_EmptyCeo {
            get {
                return ResourceManager.GetString("Error_EmptyCeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The country code of the foreign representative&apos;s citizenship is not specified.
        /// </summary>
        internal static string Error_EmptyCodeOfCitizenshipForForeignRepresentative {
            get {
                return ResourceManager.GetString("Error_EmptyCodeOfCitizenshipForForeignRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type of person who delegated authority is not specified.
        /// </summary>
        internal static string Error_EmptyDelegatorType {
            get {
                return ResourceManager.GetString("Error_EmptyDelegatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date of issue of the document certifying an individual acting without a power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyIssueDateOfDocumentProvingIdentity {
            get {
                return ResourceManager.GetString("Error_EmptyIssueDateOfDocumentProvingIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The attribute of joint powers is not specified.
        /// </summary>
        internal static string Error_EmptyJointRepresentation {
            get {
                return ResourceManager.GetString("Error_EmptyJointRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of attorney data is not filled in.
        /// </summary>
        internal static string Error_EmptyMachineReadablePowerOfAttorney {
            get {
                return ResourceManager.GetString("Error_EmptyMachineReadablePowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The expiration date of the power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPowerOfAttorneyEndDate {
            get {
                return ResourceManager.GetString("Error_EmptyPowerOfAttorneyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date of the power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPowerOfAttorneyStartDate {
            get {
                return ResourceManager.GetString("Error_EmptyPowerOfAttorneyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the data of the principal.
        /// </summary>
        internal static string Error_EmptyPrincipalOrganization {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type of principal is not specified.
        /// </summary>
        internal static string Error_EmptyPrincipalType {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It was not possible to obtain the data of an individual acting without a power of attorney.
        /// </summary>
        internal static string Error_EmptyPrincipalWithoutPowerOfAttorneyIndividual {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalWithoutPowerOfAttorneyIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The indication of the citizenship of a person acting without a power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCitizenship {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The country of citizenship code is not specified for a foreign individual acting without a power of attorney.
        /// </summary>
        internal static string Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCountryCode {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The nationality of the representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeCitizenshipType {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeCitizenshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not get the representative&apos;s details.
        /// </summary>
        internal static string Error_EmptyRepresentativeIndividual {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date of issue of the document certifying the individual representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeIndividualDocumentIssueDate {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeIndividualDocumentIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type of authorized representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeType {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The possibility of making a transfer of trust is not selected.
        /// </summary>
        internal static string Error_EmptyRetrustType {
            get {
                return ResourceManager.GetString("Error_EmptyRetrustType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The sign of an irrevocable power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyRevocationPossibleType {
            get {
                return ResourceManager.GetString("Error_EmptyRevocationPossibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The reason for revocation of the power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyRevokeReason {
            get {
                return ResourceManager.GetString("Error_EmptyRevokeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not get the data of the signatory.
        /// </summary>
        internal static string Error_EmptySigner {
            get {
                return ResourceManager.GetString("Error_EmptySigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign of citizenship is not specified.
        /// </summary>
        internal static string Error_GenCeoCitizenshipSignIsEmpty {
            get {
                return ResourceManager.GetString("Error_GenCeoCitizenshipSignIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of representative is not specified.
        /// </summary>
        internal static string Error_GenRepresentativeIsEmpty {
            get {
                return ResourceManager.GetString("Error_GenRepresentativeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all required data is filled in or the data is incorrect. Error message: {0}&quot;.
        /// </summary>
        internal static string Error_IncorrectUserCardData {
            get {
                return ResourceManager.GetString("Error_IncorrectUserCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INN is not specified in organization {0}..
        /// </summary>
        internal static string Error_InnNotSpecified {
            get {
                return ResourceManager.GetString("Error_InnNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attribute of joint exercise of authority is not specified.
        /// </summary>
        internal static string Error_JointExerIsEmpty {
            get {
                return ResourceManager.GetString("Error_JointExerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KPP is not specified in organization {0}..
        /// </summary>
        internal static string Error_KppNotSpecified {
            get {
                return ResourceManager.GetString("Error_KppNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legal address is not specified in organization {0}..
        /// </summary>
        internal static string Error_LegalAddressNotSpecified {
            get {
                return ResourceManager.GetString("Error_LegalAddressNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OGRN is not specified in organization {0}..
        /// </summary>
        internal static string Error_OgrnNotSpecified {
            get {
                return ResourceManager.GetString("Error_OgrnNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name is not specified in organization {0}..
        /// </summary>
        internal static string Error_OrgNameNotSpecified {
            get {
                return ResourceManager.GetString("Error_OrgNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The original power of attorney was not found.
        /// </summary>
        internal static string Error_OriginalPowerOfAttorneyNotFound {
            get {
                return ResourceManager.GetString("Error_OriginalPowerOfAttorneyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The parental power of attorney card is missing.
        /// </summary>
        internal static string Error_ParentalCardNotFound {
            get {
                return ResourceManager.GetString("Error_ParentalCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The power of attorney on the basis of which the transfer is carried out was not found.
        /// </summary>
        internal static string Error_ParentalPowerOfAttorneyNotFound {
            get {
                return ResourceManager.GetString("Error_ParentalPowerOfAttorneyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The information about the payment for the notarial action is not specified.
        /// </summary>
        internal static string Error_PayNotarActionIsEmpty {
            get {
                return ResourceManager.GetString("Error_PayNotarActionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date of execution (issue) of the power of attorney is not specified.
        /// </summary>
        internal static string Error_PoaDateOfIssueIsEmpty {
            get {
                return ResourceManager.GetString("Error_PoaDateOfIssueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User power of attorney card does not have ID of system power of attorney card.
        /// </summary>
        internal static string Error_PoaIDNotFoundInUserCard {
            get {
                return ResourceManager.GetString("Error_PoaIDNotFoundInUserCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of power of attorney is not specified.
        /// </summary>
        internal static string Error_PoaKindIsEmpty {
            get {
                return ResourceManager.GetString("Error_PoaKindIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position is not specified in for employee {0}..
        /// </summary>
        internal static string Error_PositionNotSpecified {
            get {
                return ResourceManager.GetString("Error_PositionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The indication of the possibility of making a transfer is not specified.
        /// </summary>
        internal static string Error_PossibilityOfSubstitutionIsEmpty {
            get {
                return ResourceManager.GetString("Error_PossibilityOfSubstitutionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected entry cannot be added due to the requirements of this POA form (a power code must contain from 6 to 255 characters).
        /// </summary>
        internal static string Error_PowerCodeLength {
            get {
                return ResourceManager.GetString("Error_PowerCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error_PowerOfAttorneyNumberNotFound.
        /// </summary>
        internal static string Error_PowerOfAttorneyNumberNotFound {
            get {
                return ResourceManager.GetString("Error_PowerOfAttorneyNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Powers are not specified.
        /// </summary>
        internal static string Error_PowersEmpty {
            get {
                return ResourceManager.GetString("Error_PowersEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power type is not specified.
        /// </summary>
        internal static string Error_PowersTypeIsEmpty {
            get {
                return ResourceManager.GetString("Error_PowersTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of powers of sole executive body is not specified.
        /// </summary>
        internal static string Error_PowersTypeOfSEBIsEmpty {
            get {
                return ResourceManager.GetString("Error_PowersTypeOfSEBIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of principal is not specified.
        /// </summary>
        internal static string Error_PrincipalTypeIsEmpty {
            get {
                return ResourceManager.GetString("Error_PrincipalTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The condition for revoking an irrevocable power of attorney is not specified.
        /// </summary>
        internal static string Error_RevocIrrevPOAIsEmpty {
            get {
                return ResourceManager.GetString("Error_RevocIrrevPOAIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The date and time of the signature is not specified.
        /// </summary>
        internal static string Error_SignTransferIrrevPOAIsEmpty {
            get {
                return ResourceManager.GetString("Error_SignTransferIrrevPOAIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Single registration number of the power of attorney is not specified.
        /// </summary>
        internal static string Error_SinglePOAregnumberIsEmpty {
            get {
                return ResourceManager.GetString("Error_SinglePOAregnumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the original power of attorney.
        /// </summary>
        internal static string Error_UnableToGetOriginalPowerOfAttorneyUserCard {
            get {
                return ResourceManager.GetString("Error_UnableToGetOriginalPowerOfAttorneyUserCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the parental power of attorney.
        /// </summary>
        internal static string Error_UnableToGetParentalPowerOfAttorneyUserCard {
            get {
                return ResourceManager.GetString("Error_UnableToGetParentalPowerOfAttorneyUserCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get authorization code from string {0}.
        /// </summary>
        internal static string Error_UnableToGetPowersCodeFromRow {
            get {
                return ResourceManager.GetString("Error_UnableToGetPowersCodeFromRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User power of attorney card {0} not found.
        /// </summary>
        internal static string Error_UserCardNotFound {
            get {
                return ResourceManager.GetString("Error_UserCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value cannot be less than {0} characters.
        /// </summary>
        internal static string Error_ValueLength {
            get {
                return ResourceManager.GetString("Error_ValueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid power of attorney format: {0}.
        /// </summary>
        internal static string InvalidPowerOfAttorneyFormat {
            get {
                return ResourceManager.GetString("InvalidPowerOfAttorneyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A signed application to revoke the power of attorney was sent to the blockchain of the Federal Tax Service of Russia.
        ///The result of the operation can be tracked in the exchange log..
        /// </summary>
        internal static string M4DRegistry_Recall_Success {
            get {
                return ResourceManager.GetString("M4DRegistry_Recall_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The power of attorney was signed and sent to the blockchain of the Federal Tax Service of Russia.
        ///The result of the operation can be tracked in the exchange log..
        /// </summary>
        internal static string M4DRegistry_Register_Success {
            get {
                return ResourceManager.GetString("M4DRegistry_Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not submitted.
        /// </summary>
        internal static string PoaDidNotSendToRegistrationStatus {
            get {
                return ResourceManager.GetString("PoaDidNotSendToRegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of attorney.
        /// </summary>
        internal static string PowerOfAttorney {
            get {
                return ResourceManager.GetString("PowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signing a machine-readable power of attorney with a cloud certificate is not currently supported.
        /// </summary>
        internal static string PowerOfAttorneyCloudSignatureWarning {
            get {
                return ResourceManager.GetString("PowerOfAttorneyCloudSignatureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when signing the power of attorney..
        /// </summary>
        internal static string PowerOfAttorneyErrorSigning {
            get {
                return ResourceManager.GetString("PowerOfAttorneyErrorSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of attorney generated.
        /// </summary>
        internal static string PowerOfAttorneyGenerated {
            get {
                return ResourceManager.GetString("PowerOfAttorneyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of attorney revoked.
        /// </summary>
        internal static string PowerOfAttorneyRevoked {
            get {
                return ResourceManager.GetString("PowerOfAttorneyRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of attorney signed.
        /// </summary>
        internal static string PowerOfAttorneySigned {
            get {
                return ResourceManager.GetString("PowerOfAttorneySigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refusal of the representative from the powers.
        /// </summary>
        internal static string RefusalOfTheRepresentativeFromThePowers {
            get {
                return ResourceManager.GetString("RefusalOfTheRepresentativeFromThePowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the type of application for revocation.
        /// </summary>
        internal static string SelectTheTypeOfApplicationForRevocation {
            get {
                return ResourceManager.GetString("SelectTheTypeOfApplicationForRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign the application.
        /// </summary>
        internal static string SignTheApplication {
            get {
                return ResourceManager.GetString("SignTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify the reason for cancellation or refusal.
        /// </summary>
        internal static string SpecifyTheReasonForCancellationOrRefusal {
            get {
                return ResourceManager.GetString("SpecifyTheReasonForCancellationOrRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following fields are required.
        /// </summary>
        internal static string TheFollowingFieldsAreRequired {
            get {
                return ResourceManager.GetString("TheFollowingFieldsAreRequired", resourceCulture);
            }
        }
    }
}
