//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowersOfAttorneyServerExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowersOfAttorneyServerExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrust of general format of powers of attorney has not been implemented.
        /// </summary>
        internal static string EmchdRetrustNotImplemented {
            get {
                return ResourceManager.GetString("EmchdRetrustNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue of identity document of head of the organization is not specified.
        /// </summary>
        internal static string Error_DateIssCEOIDDocIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateIssCEOIDDocIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue of representative&apos;s identity document is not specified.
        /// </summary>
        internal static string Error_DateIssReprIDDocIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateIssReprIDDocIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time of the signature are not specified.
        /// </summary>
        internal static string Error_DateTimeOfSignatureIsEmpty {
            get {
                return ResourceManager.GetString("Error_DateTimeOfSignatureIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country code of the foreign representative&apos;s citizenship is not specified.
        /// </summary>
        internal static string Error_EmptyCodeOfCitizenshipForForeignRepresentative {
            get {
                return ResourceManager.GetString("Error_EmptyCodeOfCitizenshipForForeignRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of issue of the document certifying an individual acting without a power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyIssueDateOfDocumentProvingIdentity {
            get {
                return ResourceManager.GetString("Error_EmptyIssueDateOfDocumentProvingIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute of joint powers is not specified.
        /// </summary>
        internal static string Error_EmptyJointRepresentation {
            get {
                return ResourceManager.GetString("Error_EmptyJointRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiration date of the power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPowerOfAttorneyEndDate {
            get {
                return ResourceManager.GetString("Error_EmptyPowerOfAttorneyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPowerOfAttorneyStartDate {
            get {
                return ResourceManager.GetString("Error_EmptyPowerOfAttorneyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of principal is not specified.
        /// </summary>
        internal static string Error_EmptyPrincipalType {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indication of the citizenship of a person acting without a power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCitizenship {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country of citizenship code is not specified for a foreign individual acting without a power of attorney.
        /// </summary>
        internal static string Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCountryCode {
            get {
                return ResourceManager.GetString("Error_EmptyPrincipalWithoutPowerOfAttorneyIndividualCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nationality of the representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeCitizenshipType {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeCitizenshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of issue of the document certifying the individual representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeIndividualDocumentIssueDate {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeIndividualDocumentIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of authorized representative is not specified.
        /// </summary>
        internal static string Error_EmptyRepresentativeType {
            get {
                return ResourceManager.GetString("Error_EmptyRepresentativeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possibility of making a transfer of trust is not selected.
        /// </summary>
        internal static string Error_EmptyRetrustType {
            get {
                return ResourceManager.GetString("Error_EmptyRetrustType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sign of an irrevocable power of attorney is not specified.
        /// </summary>
        internal static string Error_EmptyRevocationPossibleType {
            get {
                return ResourceManager.GetString("Error_EmptyRevocationPossibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of principal is not specified.
        /// </summary>
        internal static string Error_GenRepresentativeIsEmpty {
            get {
                return ResourceManager.GetString("Error_GenRepresentativeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required data is filled in or the data is incorrect. Change the data and save again&quot;.
        /// </summary>
        internal static string Error_IncorrectUserCardData {
            get {
                return ResourceManager.GetString("Error_IncorrectUserCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute of joint exercise of authority is not specified.
        /// </summary>
        internal static string Error_JointExerIsEmpty {
            get {
                return ResourceManager.GetString("Error_JointExerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The power of attorney on the basis of which the transfer is carried out was not found.
        /// </summary>
        internal static string Error_ParentalPowerOfAttorneyNotFound {
            get {
                return ResourceManager.GetString("Error_ParentalPowerOfAttorneyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information about the payment for the notarial action is not specified.
        /// </summary>
        internal static string Error_PayNotarActionIsEmpty {
            get {
                return ResourceManager.GetString("Error_PayNotarActionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of execution (issue) of the power of attorney is not specified.
        /// </summary>
        internal static string Error_PoaDateOfIssueIsEmpty {
            get {
                return ResourceManager.GetString("Error_PoaDateOfIssueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User power of attorney card does not have ID of system power of attorney card.
        /// </summary>
        internal static string Error_PoaIDNotFoundInUserCard {
            get {
                return ResourceManager.GetString("Error_PoaIDNotFoundInUserCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of power of attorney is not specified.
        /// </summary>
        internal static string Error_PoaKindIsEmpty {
            get {
                return ResourceManager.GetString("Error_PoaKindIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indication of the possibility of making a transfer is not specified.
        /// </summary>
        internal static string Error_PossibilityOfSubstitutionIsEmpty {
            get {
                return ResourceManager.GetString("Error_PossibilityOfSubstitutionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power type is not specified.
        /// </summary>
        internal static string Error_PowersTypeIsEmpty {
            get {
                return ResourceManager.GetString("Error_PowersTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of powers of sole executive body is not specified.
        /// </summary>
        internal static string Error_PowersTypeOfSEBIsEmpty {
            get {
                return ResourceManager.GetString("Error_PowersTypeOfSEBIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of principal is not specified.
        /// </summary>
        internal static string Error_PrincipalTypeIsEmpty {
            get {
                return ResourceManager.GetString("Error_PrincipalTypeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition for revoking an irrevocable power of attorney is not specified.
        /// </summary>
        internal static string Error_RevocIrrevPOAIsEmpty {
            get {
                return ResourceManager.GetString("Error_RevocIrrevPOAIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time of the signature is not specified.
        /// </summary>
        internal static string Error_SignTransferIrrevPOAIsEmpty {
            get {
                return ResourceManager.GetString("Error_SignTransferIrrevPOAIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Single registration number of the power of attorney is not specified.
        /// </summary>
        internal static string Error_SinglePOAregnumberIsEmpty {
            get {
                return ResourceManager.GetString("Error_SinglePOAregnumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User power of attorney card {0} not found.
        /// </summary>
        internal static string Error_UserCardNotFound {
            get {
                return ResourceManager.GetString("Error_UserCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid power of attorney format: {0}.
        /// </summary>
        internal static string InvalidPowerOfAttorneyFormat {
            get {
                return ResourceManager.GetString("InvalidPowerOfAttorneyFormat", resourceCulture);
            }
        }
    }
}
